[tools]
bun = "latest"
"github:BurntSushi/ripgrep" = "latest"
"github:neovim/neovim" = "latest"
go = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
node = "latest"
"npm:mcp-hub" = "latest"
"npm:tldr" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:zx" = "latest"
pnpm = "latest"
python = "latest"
rust = "latest"
uv = "latest"
