[tools]
node = "latest"
pnpm = "latest"
bun = "latest"
python = "latest"
uv = "latest"
rust = "latest"
go = "latest"
"github:neovim/neovim" = "latest"
"go:github.com/jesseduffield/lazygit" = "latest"
"npm:tldr" = "latest"
"npm:zx" = "latest"
